"""add article columns

Revision ID: be7059ff4ee9
Revises: 4a63a0ce8bb0
Create Date: 2025-08-09 19:19:30.133737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7059ff4ee9'
down_revision = '4a63a0ce8bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('preview', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('minutes_to_read', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_articles_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_articles_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('minutes_to_read')
        batch_op.drop_column('preview')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
